### ISSUE TITLE
Feature Request / Question : Port to other chips / Board development

### ISSUE THREAD

**Issue by chepo92** [BusPirate/Bus_Pirate#142]
How hard would it be to port the code and compile for other chip?

Also there seems to be no board development for years, what about a new one?, or even better, make the bus pirate firmware uC agnostic (or at least port to more friendly non-PIC uC, and 32bit) 

Anyone there?

**Comment by kallisti5** [comment]
Hi!  All of this code is pretty specific to the Bus Pirate's PIC hardware.

The BusPirate v4 uses a "still fully supported" https://www.microchip.com/wwwproducts/en/PIC24FJ256GB106

The BusPirate v4 really isn't "unstable" as all the older sites say.. It was "less stable", but this repo refined away a lot of the stability issues early on that Dangerous Prototypes never fixed.


The BusPirate hardware is open source, so you technically could build your own.
Since there isn't much reason to target other boards and devices (and PIC code isn't super portable). I'm closing this one.
